# Generated by Codex on 2026-01-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_serviceusage"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="can_use_advanced_tools",
            field=models.BooleanField(default=False),
        ),
    ]
